"""Add created at to Artist and Venue

Revision ID: dc908a4d42e1
Revises: 709722e7d87c
Create Date: 2020-11-07 03:13:51.710164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc908a4d42e1'
down_revision = '709722e7d87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('venues', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_at')
    op.drop_column('artists', 'created_at')
    # ### end Alembic commands ###
